config/routes.rb
Newage::Application.routes.draw do
 
  devise_for :users
  devise_scope :user do
   get "login", :to => "devise/sessions#new"
   get "logout", :to => "devise/sessions#destroy"
  end

  mount ImperaviRails::Engine => "/imperavi"

  resource :location, :only =>[:edit,:update], :defaults => { :id =>1 }
  resources :feedbacks, :only => [:new, :create]

  resources :images, :only => [:index, :create]

  resources :articles do
    resource :metaitems, :only => [:edit, :update]
  end

  root :to => 'articles#index'
  
  match '/:id' => 'articles#show', :constraints => { :id => /\d.+/ }
  
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_one :metaitem, :dependent => :destroy
	
	has_many :childs, :class_name=>'Article', :foreign_key => 'parent_id', :dependent => :destroy
	belongs_to :father, :class_name=>'Article', :foreign_key => 'parent_id'

	validates :name, :slug, :presence =>true, :length => {:maximum => 255}
	
	validates :position, :parent_id, :numericality => {:only_integer => true}
	validates :home, :uniqueness => true, :if => 'self.home' #validate if home checked
	
    scope :top, where('top = true')
    scope :desc, order('position DESC')

	def to_param
		"#{id}-#{slug}"
	end
    
    #def set_home?
    #	self.home == true
    #end
	#def check_home
	#	if self.home == true
	#		validates :home, :uniqueness => true
	#	end
	#end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates :name, :email, :title, :presence => true, :length => {:maximum => 255}
  validates :message, :presence => true
  validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
end

app/models/image.rb
class Image < ActiveRecord::Base
  image_accessor :image # accessor to image_uid

  validates :image, :presence => true, :on => :create
  validates :image, :length => { :maximum => 6.megabytes }

  # Dragonfly custom validators for image
  # see: github.com/markevans/dragonfly
  validates_property :format,    :of => :image, :in => [:jpeg, :jpg, :png, :JPEG, :JPG, :PNG]
  validates_property :mime_type, :of => :image, :in => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
  validates_property :width,     :of => :image, :in => (150..3000)
  validates_property :height,    :of => :image, :in => (150..3000)

  default_scope order(:updated_at)
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates :phone1, :phone2, :adress, :sitename, :copyright, :length => {:maximum => 255}
	validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}, :presence => true
end

app/models/metaitem.rb
class Metaitem < ActiveRecord::Base
  belongs_to :article

  validates :title, :length => {:maximum => 255}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from Exception, :with => :handle_exceptions
  before_filter :authenticate_user!, :except => [:show,:index]

  def handle_exceptions(e)
   case e
   when ActiveRecord::RecordNotFound
   	not_found
   else
   	internal_error(e)
   end
  end

  def not_found
   render 'application/not_found',:status => 404
  end

  def internal_error(e)
    if Rails.env.production?
      render 'application/internal_error', :status => 500, :layout => false
    else
      raise
    end
  end
  
end

app/controllers/articles_controller.rb
# encoding: utf-8
class ArticlesController < ApplicationController
  
  respond_to :html
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  
  def edit
    @article = Article.find(params[:id])
  end

 
  def create
    @article = Article.new(params[:article])

    if @article.save
      flash[:notice] = "Раздел успешно создан"
      redirect_to @article
    else
      flash[:alert] = "При создании раздела произошли ошибки"
      render :action => "new"
    end
  end


  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      flash[:notice] = "Раздел успешно обновлен"
      redirect_to @article
    else
      flash[:alert] = "При обновлении раздела произошли ошибки"
      render :action => "edit"
    end
  end

  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_url
  end
end

app/controllers/feedbacks_controller.rb
# encoding: utf-8
class FeedbacksController < ApplicationController
  skip_before_filter :authenticate_user!
  respond_to :html
  def new
  	@feedback = Feedback.new
  end

   def create
    @feedback = Feedback.new(params[:feedback])

    if @feedback.valid?
      admin_email = Location.first.email
      #admin_email = 'pop-corm2@ya.ru'
      
      if FeedbackMailer.notify(@feedback,admin_email)
        flash[:notice] = "Ваше сообщение отправлено"
        redirect_to :root
      else
    	  flash[:alert] = "Не удалось отправить сообщение"
        render :action => "new"
      end

    else
      flash[:alert] = "При заполнении формы произошли ошибки"
      render :action => 'new'
    end
  end

  def human?
    @feedback.antispam.blank? ? true : false
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  #skip_before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token
  respond_to :html, :json

  def index
    @images = Image.scoped

    respond_with @images do |format|
      format.json { render :json => json_images(@images), :layout => false }
    end
  end

  def create
    @image = Image.new(params[:image])

    if @image.save
      render :text => view_context.image_tag(resize_image(@image, '700x1000>').url, :alt => '')
    else
      render :json => @image.errors
    end
  end

private

  def json_images(images)
    json_images = []

    images.each do |image|
      json_images << {
        :thumb => crop_image(image, 120, 100).url,
        :image => resize_image(image, '700x1000>').url
      }
    end

    json_images
  end

  def resize_image(image,size)
    image.image.thumb(size)
  end

  def crop_image(image, width = 100, height = 100, gravity = :c)
    image.image.process(:resize_and_crop, :width => width, :height => height, :gravity => gravity.to_s)
  end
end

app/controllers/locations_controller.rb
# encoding: utf-8
class LocationsController < ApplicationController
 
  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    
    if @location.update_attributes(params[:location])
      flash[:notice] = "Данные успешно сохранены"
      redirect_to :root
    else
      flash[:alert] = "При сохранении произошли ошибки"
      render :action => "edit"
    end
  end

end

app/controllers/metaitems_controller.rb
class MetaitemsController < ApplicationController
  before_filter :find_article

  def edit
    if @article.metaitem.present?
      @metaitem = @article.metaitem
    else
      @metaitem = @article.build_metaitem
    end
  end
 
  def update
    if @article.metaitem.present?
      @metaitem = @article.metaitem
      @metaitem.attributes = params[:metaitem]
    else
      @metaitem = @article.build_metaitem(params[:metaitem])
    end
    
    if @metaitem.save
      flash[:notice] = "Saved"
    else
      flash[:alert] = "Error"
    end
    
    redirect_to show_article_path(@article)
  end

  private
    def find_article
      @article = Article.find(params[:article_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
# encoding: utf-8
module ArticlesHelper
	def parent_article_options(article)
		root = [['без родителя',0]]
		parents = Article.where(:parent_id=>0, :top => false)
		if article.try(:id).present?
			parents = parents.select { |a| a.id != article.id }		
		end
		options_for_select(root + parents.collect { |p| [p.name, p.id]},article.try(:parent_id))
	end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/metaitems_helper.rb
module MetaitemsHelper
end

app/views/application/internal_error.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  <title>500 Ошибка</title> 
</head>
<body>
  <h1> 500 Ошибка</h1>
  <p>
    Произошла ошибка. Уже исправляем.
  </p>
</body>
<html>

app/views/application/not_found.html.erb
<h1> Ошибка 404</h1>

<p>
  Страница не найдена
</p>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>*<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %>*<br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :cols => '128' %>
  </div>
  <div class="field">
    <%= f.label :position %>*<br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :home %><br />
    <%= f.check_box :home %>
  </div>
  <div class="field">
    <%= f.label :top %><br />
    <%= f.check_box :top %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= select_tag 'article[parent_id]', parent_article_options(@article) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= render 'shared/imperavi_editor', :target => :article_body %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>Body</th>
    <th>Position</th>
    <th>Home</th>
    <th>Parent</th>
    <th>Metaitem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.name %></td>
    <td><%= article.slug %></td>
    <td><%= article.body %></td>
    <td><%= article.position %></td>
    <td><%= article.home %></td>
    <td><%= article.parent_id %></td>
    <td><%= article.metaitem_id %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @article.name %>
</p>

<p>
  <b>Slug:</b>
  <%= @article.slug %>
</p>

<p>
  <b>Body:</b>
  <%= @article.body %>
</p>

<p>
  <b>Position:</b>
  <%= @article.position %>
</p>

<p>
  <b>Home:</b>
  <%= @article.home %>
</p>

<p>
  <b>Parent:</b>
  <%= @article.parent_id %>
</p>

<p>
  <b>Metaitem:</b>
  <%= @article.metaitem_id %>
</p>

<% if @article.metaitem.present? %>
 <%= @article.metaitem.to_json %>
<% end %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= f.label :name %>*<br />
   <%= f.text_field :name %>
  </div>
  <div class="field">
   <%= f.label :email %>*<br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
   <%= f.label :title %>*<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= f.label :message %>*<br />
    <%= f.text_area :message %>
  </div>
  <div style = "display:none">
   <%= f.text_field :antispam %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/feedbacks/new.html.erb
<h1>Feedback#new</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% if user_signed_in? %>
  <%= render "shared/toolbar" %>
  <%= render "shared/flash_messages"%>
<% end %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :adress %><br />
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label :email %>*<br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :sitename %><br />
    <%= f.text_field :sitename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

app/views/metaitems/_form.html.erb
<%= form_for [@article,@metaitem], :method => :put do |f| %>
  <% if @metaitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metaitem.errors.count, "error") %> prohibited this metaitem from being saved:</h2>

      <ul>
      <% @metaitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

app/views/metaitems/edit.html.erb
<h1>Editing metaitem</h1>

<%= render 'form' %>

<%#= link_to 'Show', @metaitem %> |
<%#= link_to 'Back', metaitems_path %>

app/views/shared/_flash_messages.html.erb
<% if notice %>
 <script type= "text/javascript">
   humane.waitForMove = true;
   humane.success("<%= notice%>");
 </script> 
<% else if alert %>
  <script type= "text/javascript">
    humane.waitForMove = true;
    humane.error("<%= alert%>");
  </script>
  <% end %> 
<% end %>

app/views/shared/_imperavi_editor.html.erb
<%= include_imperavi_stylesheet %>
<%= include_imperavi_javascript %>
<%= imperavi target,
  :paths => {
    :images => {
      # Path to upload handler
      :upload => images_path,

      # Path to list of images
      :list   => images_path(:format => :json)
    }
  }
%>

app/views/shared/_toolbar.html.erb
<div id="toolbar">
 <ul>
  <li><%= link_to "Добавить раздел", new_article_path %></li>
 <% if @article.present? %>
    <li><%=  link_to "Изменить раздел", edit_article_path(@article) %></li>
    <li><%= link_to "Удалить раздел", @article, confirm: "Вы уверены?", method: :delete  %></li>
    <li><%= link_to "Метаданные раздела", edit_article_metaitems_path(@article) %></li>
 <% end %>
   <li><%= link_to "Настройки", edit_location_path %></li>
   <li><%= link_to "Выход", destroy_user_session_path %></li>
 </ul>
</div>